### ISSUE TITLE
Feature testing

### ISSUE THREAD

**Issue by johnlindquist** [johnlindquist/angularjs-plugin#18]
## Installation

Download: https://dl.dropbox.com/u/132579/angularjs-plugin.jar
Install: File->Settings->Plugins. "Install plugin from disk", select the .jar you just downloaded
### Navigation

Press ctrl (or cmd) + 1 to open the Navigator
- Report if performance is ok when opening
- Report if it's finding everything you'd expect it to
- Report if it's navigating to proper locations after selecting
- Suggest if you'd like it to find anything else
- Suggest UI improvements
### Auto }} insertion

In HTML files, typing "{{" should automatically insert the closing "}}"
- Report if you find any issues with it

**Comment by dakra** [comment]
The Navigation doesn't open on the newest pycharm EAP.

Error message: com/intellij/psi/util/PsiUtil: com/intellij/psi/util/PsiUtil

Details:

```
com/intellij/psi/util/PsiUtil: com/intellij/psi/util/PsiUtil
java.lang.NoClassDefFoundError: com/intellij/psi/util/PsiUtil
    at org.angularjs.GotoAngularAction$2$1.process(GotoAngularAction.java:145)
    at org.angularjs.GotoAngularAction$2$1.process(GotoAngularAction.java:132)
    at com.intellij.usages.UsageInfo2UsageAdapter.processRangeMarkers(UsageInfo2UsageAdapter.java:205)
    at org.angularjs.GotoAngularAction$2.run(GotoAngularAction.java:132)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:929)
    at org.angularjs.GotoAngularAction.getValidResults(GotoAngularAction.java:177)
    at org.angularjs.GotoAngularAction.gotoActionPerformed(GotoAngularAction.java:78)
    at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:60)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:480)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.util.PsiUtil PluginClassLoader[AngularJS, 0.1.6]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 20 more
```

**Comment by ffesseler** [comment]
A bit slow to open (20sec first time, then about 5sec each time) until I noticed it also parsed my node_modules folder. Now that I've exluded the folder, it's less than a sec! (for about 300 elements)

Note that by default, Ctrl+1 is used to navigate to bookmark 1 so the menu doesn't show up. 

Otherwise everything works as expected, great job!

**Comment by johnlindquist** [comment]
@dakra Thanks, I'll look into it.
@ffesseler ah, good point, I'll have to try to exclude node_modules by default.

**Comment by ffesseler** [comment]
Or maybe let the dev choosing which folders to exclude ? 
Because it will also parse some other folders you don't want to such as third-party libs or build js files.

On a side note, it would be great also to navigate to html templates/partials.

**Comment by johnlindquist** [comment]
@ffesseler yeah, I'll have to think about how to set up exclusions. People generally hate configuring things.

What do you mean "navigate to html templates/partials"? You mean look for "ng-template" tags?

**Comment by ffesseler** [comment]
I mean include html files used as templates in the navigation list (by their file name).
They could be templates referenced by ng-template, ng-include or templateUrl delacred inside directives or $routeProvider

**Comment by swizard** [comment]
3:53:02 NoClassDefFoundError: com/intellij/psi/util/PsiUtil: com/intellij/psi/util/PsiUtil 
same error with webstorm 6.0.1 build #WS-127.122

**Comment by tiw** [comment]
+1 same error phpstorm 6.0.2 PS-129.487 ﻿
