### ISSUE TITLE
Getting error in Intellij console.

### ISSUE THREAD

**Issue by socket70** [johnlindquist/angularjs-plugin#26]
I haven't been able to tell when this actually happens. The plug in seems to work correctly, but I will occassionally get this IDE Fatal Error in the IDE.

com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V
java.lang.NoSuchMethodError: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V
    at org.angularjs.GotoAngularAction.getAngularUsages(GotoAngularAction.java:190)
    at org.angularjs.GotoAngularAction.gotoActionPerformed(GotoAngularAction.java:80)
    at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:60)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by socket70** [comment]
Forgot to mention this is version 0.1.8.

**Comment by grettke** [comment]
Linux vela 3.5.0-37-generic #58~precise1-Ubuntu SMP Wed Jul 10 17:48:11 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

java -version
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

JetBrain WebStorm 6.0.2
Build #WS129-664

Error: Install most recent plugin release 0.1.8, hit C:l, 

NoSuchMethodError: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V

**Comment by denofevil** [comment]
This issue should be fixed with JetBrains/intellij-plugins@1ddd37c13c64ad31d7397d8472b950cb65c8fbc2
