### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Tjorriemorrie** [johnlindquist/angularjs-plugin#28]
```
com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V
java.lang.NoSuchMethodError: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V
    at org.angularjs.GotoAngularAction.getAngularUsages(GotoAngularAction.java:190)
    at org.angularjs.GotoAngularAction.gotoActionPerformed(GotoAngularAction.java:80)
    at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:60)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

File:

```
'use strict'

angular.module('browse', [])

    .controller('browseHomeCtrl', ['$scope', 'exchangesFctr', function($scope, exchangesFctr) {
        $scope.exchanges = exchangesFctr.get(); // used shortcut here on fctr
    }])
```

**Comment by kozmic** [comment]
+1

Windows 7 64 bit, IntelliJ IDEA 12.1.4, AngularJS plugin 0.1.8

**Comment by jarst** [comment]
+1
0.1.8 on IntelliJ IDEA 12.1.4

This issue is a duplicate of [issue 26](https://github.com/johnlindquist/angularjs-plugin/issues/26)

**Comment by bewilcox** [comment]
+1

**Comment by hho** [comment]
Same here.
Is there any way to get the old version back? (You know, for people who are actually on IDEA and not on a Webstorm preview)

**Comment by denofevil** [comment]
You can download previous version manually from [plugin repository](http://plugins.jetbrains.com/plugin/6971) by clicking on Show all versions under versions table.
This issue should be fixed with JetBrains/intellij-plugins@1ddd37c13c64ad31d7397d8472b950cb65c8fbc2
