### ISSUE TITLE
Completely breaks intentions in IntelliJ 11.1.5

### ISSUE THREAD

**Issue by OverZealous** [johnlindquist/angularjs-plugin#31]
When installed in IntelliJ IDEA 11.1.5, this plugin completely stops intentions from working (ie: the lightbulb dropdown).

The log reveals this error:

```
2013-07-31 15:54:15,142 [ 257682]  ERROR - currency.PrioritizedFutureTask - IntelliJ IDEA 11.1.5  Build #IU-117.1056 
2013-07-31 15:54:15,142 [ 257682]  ERROR - currency.PrioritizedFutureTask - JDK: 1.6.0_51 
2013-07-31 15:54:15,143 [ 257683]  ERROR - currency.PrioritizedFutureTask - VM: Java HotSpot(TM) 64-Bit Server VM 
2013-07-31 15:54:15,143 [ 257683]  ERROR - currency.PrioritizedFutureTask - Vendor: Apple Inc. 
2013-07-31 15:54:15,143 [ 257683]  ERROR - currency.PrioritizedFutureTask - OS: Mac OS X 
2013-07-31 15:54:15,143 [ 257683]  ERROR - currency.PrioritizedFutureTask - Last Action: ShowLog 
2013-07-31 15:54:15,143 [ 257683]  ERROR - currency.PrioritizedFutureTask - Original exception:  
java.lang.NoClassDefFoundError: com/intellij/codeInsight/intention/impl/QuickEditAction
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:125)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:121)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:97)
    at com.intellij.ide.plugins.cl.PluginClassLoader.d(PluginClassLoader.java:102)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:38)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:58)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:45)
    at com.intellij.codeInsight.intention.IntentionActionBean.instantiate(IntentionActionBean.java:75)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getDelegate(IntentionActionWrapper.java:75)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFamilyName(IntentionActionWrapper.java:48)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.getFullFamilyName(IntentionActionWrapper.java:65)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.b(IntentionManagerSettings.java:127)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.isEnabled(IntentionManagerSettings.java:140)
    at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.getAvailableIntentionActions(IntentionManagerImpl.java:215)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:202)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.b(ShowIntentionsPass.java:154)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:128)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:350)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1053)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:342)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:218)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:340)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:316)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:134)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:131)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassNotFoundException: com.intellij.codeInsight.intention.impl.QuickEditAction PluginClassLoader[AngularJS, 0.1.8]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 42 more
```

**Comment by johnlindquist** [comment]
I built/tested this plugin on IntelliJ 12. I have no plans for testing or making compatible with 11.
