### ISSUE TITLE
Can't open terminal session:class with name "org.angularjs.GotoAngularAction" not found [Plugin: AngularJS]

### ISSUE THREAD

**Issue by underdogcoder** [johnlindquist/angularjs-plugin#41]
I installed the plugin on Intellij 13 Ultimate.

Can't open terminal session:class with name "org.angularjs.GotoAngularAction" not found [Plugin: AngularJS]: class with name "org.angularjs.GotoAngularAction" not found [Plugin: AngularJS]
com.intellij.diagnostic.PluginException: class with name "org.angularjs.GotoAngularAction" not found [Plugin: AngularJS]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:262)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:232)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:225)
    at org.jetbrains.plugins.terminal.JBTerminalPanel.registerKeymapActions(JBTerminalPanel.java:87)
    at org.jetbrains.plugins.terminal.JBTerminalPanel.<init>(JBTerminalPanel.java:74)
    at org.jetbrains.plugins.terminal.JBTerminalWidget.createTerminalPanel(JBTerminalWidget.java:31)
    at org.jetbrains.plugins.terminal.JBTerminalWidget.createTerminalPanel(JBTerminalWidget.java:17)
    at com.jediterm.terminal.ui.JediTermWidget.<init>(JediTermWidget.java:55)
    at com.jediterm.terminal.ui.JediTermWidget.<init>(JediTermWidget.java:40)
    at org.jetbrains.plugins.terminal.JBTerminalWidget.<init>(JBTerminalWidget.java:20)
    at org.jetbrains.plugins.terminal.JBTabbedTerminalWidget.createInnerTerminalWidget(JBTabbedTerminalWidget.java:86)
    at com.jediterm.terminal.ui.TabbedTerminalWidget.createTerminalSession(TabbedTerminalWidget.java:58)
    at org.jetbrains.plugins.terminal.AbstractTerminalRunner.openSession(AbstractTerminalRunner.java:142)
    at org.jetbrains.plugins.terminal.AbstractTerminalRunner.openSession(AbstractTerminalRunner.java:177)
    at org.jetbrains.plugins.terminal.AbstractTerminalRunner.createTerminalWidget(AbstractTerminalRunner.java:96)
    at org.jetbrains.plugins.terminal.TerminalView.createTerminalInContentPanel(TerminalView.java:114)
    at org.jetbrains.plugins.terminal.TerminalView.initTerminal(TerminalView.java:62)
    at org.jetbrains.plugins.terminal.TerminalToolWindowFactory.createToolWindowContent(TerminalToolWindowFactory.java:17)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:449)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$11.run(ToolWindowManagerImpl.java:528)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: org.angularjs.GotoAngularAction PluginClassLoader[AngularJS, 0.1.9]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:255)
    ... 37 more

**Comment by denofevil** [comment]
This problem should be fixed with JetBrains/intellij-plugins@1ddd37c13c64ad31d7397d8472b950cb65c8fbc2.
