### ISSUE TITLE
Exception thrown when using Cmd+? to comment out line of HTML

### ISSUE THREAD

**Issue by tennisgent** [johnlindquist/angularjs-plugin#42]
I get the following exception in WebStorm 8 EAP every time I try to use the Cmd+? shortcut to comment out a line of HTML code.

It actually comments out the line, but then when I hit Cmd+? again, it does not uncomment the line.

After patch: doc:
'pageText.hello'
---PSI:
''
---chars:
''.
Language: AngularJS;
 Host file: HtmlFile:header.html in '/projects/xactcredentials/GUI/xcr/global/html/header.html'
Context element (344,424): 'XmlText'; Ranges: [Shred (344,424): XmlText Inhost range: (355,369); PSI range: (0,0)]: After patch: doc:
'pageText.hello'
---PSI:
''
---chars:
''.
Language: AngularJS;
 Host file: HtmlFile:header.html in '/projects/xactcredentials/GUI/xcr/global/html/header.html'
Context element (344,424): 'XmlText'; Ranges: [Shred (344,424): XmlText Inhost range: (355,369); PSI range: (0,0)]
java.lang.AssertionError: After patch: doc:
'pageText.hello'
---PSI:
''
---chars:
''.
Language: AngularJS;
 Host file: HtmlFile:header.html in '/projects/xactcredentials/GUI/xcr/global/html/header.html'
Context element (344,424): 'XmlText'; Ranges: [Shred (344,424): XmlText Inhost range: (355,369); PSI range: (0,0)]
    at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.doneInjecting(MultiHostRegistrarImpl.java:257)
    at org.angularjs.editor.AngularJSInjector.getLanguagesToInject(AngularJSInjector.java:41)
    at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:456)
    at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
    at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.compute(InjectedPsiCachedValueProvider.java:51)
    at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.compute(InjectedPsiCachedValueProvider.java:38)
    at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:199)
    at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:219)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:120)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:96)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.hasInjections(InjectedLanguageUtil.java:418)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:51)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:122)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:65)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:53)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:175)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.a(SharedPsiElementImplUtil.java:67)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:63)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.findReferenceAt(CompositePsiElement.java:116)
    at com.intellij.psi.SingleRootFileViewProvider.a(SingleRootFileViewProvider.java:423)
    at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:395)
    at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:613)
    at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:116)
    at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:301)
    at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1150)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:368)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:194)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by denofevil** [comment]
This issue is fixed in JetBrains/intellij-plugins@da244f96c593b2ed0d139e8cbcd7a618d50e1d6b
